### ISSUE TITLE
Whitelist feature

### ISSUE THREAD

**Issue by MitSchnitzel** [XNBlank/PkHeX-EggLocke-Generator#4]
Hi! Is there any possibility to use a whitelist instead of a blacklist? It would be super nice for a Monolocke :)

**Comment by XNBlank** [comment]
I assume Monolocke is a single typing? I could look into doing an invert button for the blacklist settings.

**Comment by XNBlank** [comment]
The ability to invert blacklisted Pokemon will be available in the next version. 👍
